### ISSUE TITLE
Unrecognized field "clientSessionIdleTimeout" while creating Clients

### ISSUE THREAD

**Issue by Coleslaw3557** [kiwigrid/keycloak-client-controller#33]
Hey there, hoping someone can point me in the right direction where to troubleshoot. I've been trying to create client scopes and clients unsuccessfully; however realms create just fine.

Using the example client creation below:
```
apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: some-client
spec:
  keycloak: keycloak
  realm: gubbins
  clientId: some-client
  clientType: public
  defaultClientScopes:
    - realmhelm-scope
```

Gives me the following on the controller:

```
00:48:25.390 96.0.1/... ERROR     com.kiwigrid.keycloak.controller.client.ClientController Failed to ADDED resource gubbins/some-client.
javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clientSessionIdleTimeout" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (126 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "notBefore", "publicKey", "smtpServer", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "attributes", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings", "displayName", "refreshTokenMaxReuse", "oauthClients", "defaultGroups", "browserFlow" [truncated]])
 at [Source: (org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper); line: 1, column: 469] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["clientSessionIdleTimeout"])
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:156)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy59.toRepresentation(Unknown Source)
        at com.kiwigrid.keycloak.controller.client.ClientController.lambda$realm$2(ClientController.java:161)
        at java.base/java.util.Optional.filter(Optional.java:223)
        at com.kiwigrid.keycloak.controller.client.ClientController.realm(ClientController.java:159)
        at com.kiwigrid.keycloak.controller.client.ClientController.apply(ClientController.java:48)
        at com.kiwigrid.keycloak.controller.client.ClientController.apply(ClientController.java:28)
        at com.kiwigrid.keycloak.controller.KubernetesController.eventReceived(KubernetesController.java:67)
        at com.kiwigrid.keycloak.controller.KubernetesController.eventReceived(KubernetesController.java:14)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:232)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clientSessionIdleTimeout" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (126 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "notBefore", "publicKey", "smtpServer", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "attributes", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings", "displayName", "refreshTokenMaxReuse", "oauthClients", "defaultGroups", "browserFlow" [truncated]])
 at [Source: (org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper); line: 1, column: 469] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["clientSessionIdleTimeout"])
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:375)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:268)
        at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:231)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:120)
        ... 24 common frames omitted
```

I'm not sure if it matters or not but I am running Keycloak 11.0.1. Maybe some new fields were added and that's what it's complaining about?

**Comment by chrodriguez** [comment]
Hi @timothydlister , I found a similar error when updating a realm CRD configured against a Keycloak 11 instance. It seems that the keycloak api used by keycloak controller inside docker image version 2.0.0 is old. After upgrading controller docker image to 3.0.0 (build using updated maven keycloak 11 dependencies) it worked!

Tell me if upgrading controller works for you

**Comment by Coleslaw3557** [comment]
@chrodriguez, Thank you! Looks like that's what it was. Pulling the 3.0.0 version of the docker image fixed my issue. I hadn't realized that the helm chart was set to pull 2.0.0 by default.

Cheers,
